apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: techchallenge
type: Opaque
data:
  REDIS_URL: pos-togmaster-dev-redis.wlpcva.0001.use1.cache.amazonaws.com:6379
  SERVICE_API_KEY: U1VBX0NIQVZFX0RFX1NFUlZJQ08=
  AWS_SQS_URL: https://sqs.us-east-1.amazonaws.com/712819938659/pos-togmaster-dev-queue