apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: techchallenge
type: Opaque
stringData:
  aws_access_key_id: SUA_ACCESS_KEY
  aws_secret_access_key: SUA_SECRET_KEY
  aws_sqs_url: https://sqs.us-east-1.amazonaws.com/123456789012/sua-fila