apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  namespace: techchallenge
type: Opaque
stringData:
  database_url: "postgres://USER:PASSWORD@SEU-RDS.amazonaws.com:5432/targeting_db"