apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: techchallenge
type: Opaque
stringData:
  DATABASE_URL: "postgres://appuser:SUA_SENHA@seu-rds.xxxxxx.us-east-1.rds.amazonaws.com:5432/auth_db?sslmode=require"
  MASTER_KEY: "admin-secreto-123"